### ISSUE TITLE
Split configuration.nix into multiple submodules

### ISSUE THREAD

**Issue by ymstnt** [tchfoo/raspi-dotfiles#2]
Currently, only the `home` config files and the `hosts/raspi-doboz` config are separated, everything else is in one file, `configuration.nix` and it's starting to become a little too crowded.
Sure, search in the file works, but there is not much logic where new config should be placed and sometimes there can be conflicts as well. Additionally, separate submodules can be easier to see through and organize.

I propose, we should split the large `configuration.nix` file into separate submodules under a `modules/` folder.
The only downside I see is having to remember to `git add` a new submodule for it to work.

There are few things we need to consider:
- We could use the usual `allImportsExcept` in the `modules/default.nix` but since we only have one host, it is probably not needed. However, it could be used to temporarily disable modules.
- Some modules have nginx related config. It might be better to split the nginx config, and every affected submodule would have its own nginx config part.
- We should discuss how we are planning to split the miscellaneous config, I'm mainly talking about the beginning and end of `configuration.nix`, settings like timezone, but also creating directories, installing packages, creating users etc.

**Comment by gepbird** [comment]
> We should discuss how we are planning to split the miscellaneous config, I'm mainly talking about the beginning and end of configuration.nix, settings like timezone, but also creating directories, installing packages, creating users etc.

For creating directories, we can put the `systemd.tmpfiles.rules` configs to the related modules. I'd put the other misc configs like timezone into a `system` module.

It's also good for group related config that were scattered previously: for example moe has some config in `systemd.tmpfiles.rules`, `age.secrets`, `services.borgmatic` and of course `moe`.

I think we should also turn our `home` configs into modules too.
